import asyncio
import uuid
from loguru import logger
from client import SyndicateClient

# The Agent's simulated brain and identity
AGENT_ID = f"SniperNode-{str(uuid.uuid4())[:8]}"

async def process_lead(lead, client, AGENT_ID):
    logger.info(f"🔎 Lead ID: {lead['id']} | Context: {lead['description'][:50]}... | Min Bid: {lead['min_bid_cents']}¢")

    # Simple heuristic: Always bid on Princeton/Perplexity leads
    bid_amount = lead['min_bid_cents'] + 20

    # 4. Place the bid
    logger.info(f"🎯 Placing aggressive bid of {bid_amount}¢ on Auction {lead['id']}")
    try:
        bid_res = await client.place_bid(
            auction_id=lead['id'],
            agent_id=AGENT_ID,
            bid_amount_cents=bid_amount
        )
        logger.success(f"🏅 Bid Accepted! ID: {bid_res['bid_id']}")
    except Exception as e:
        logger.error(f"❌ Bid Failed: {e}")
        return

    # 5. Settle the Action (In reality, other agents would bid and time would expire)
    # We instantly settle to simulate winning and handing the 20% tax to the Syndicate
    logger.info("⏳ Attempting to settle and claim the optimization task...")
    settle_res = await client.settle_auction(auction_id=lead['id'])

    net_payout = settle_res['net_payout_cents']
    house_tax = settle_res['syndicate_tax_cents']

    logger.success(f"🥂 AUCTION WON! Handing 20% Tax ({house_tax}¢) back to the House.")
    logger.info(f"💸 Net Agent Payout remaining for logic: {net_payout}¢")

async def run_sniper():
    logger.info(f"🤖 Booting Syndicate Sniper Agent [{AGENT_ID}]")
    
    # 1. Initialize SDK Using Sandbox Auth
    async with SyndicateClient(api_key="syndicate_agent_v0.1_key") as client:
        try:
            # 2. Check the Syndicate API for high-intent leads generated by Syla/Hunter
            logger.info("📡 Scanning Syndicate Command for Open Leads...")
            leads = await client.get_open_leads()
            
            if not leads:
                logger.warning("No open auctions found. Syla must be sleeping.")
                return
                
            logger.success(f"🔍 Found {len(leads)} active GEO leads.")
            
            # ⚡ Bolt Optimization: Batch credit top-up before the loop
            # Calculating requirements beforehand and running a single API call
            # reduces network requests from O(N) to O(1).
            total_required_cents = sum(lead['min_bid_cents'] + 20 for lead in leads)
            package_type = "pro" if total_required_cents > 1000 else "starter"
            logger.info(f"💳 Executing Batch MPP Credit Top-up for {total_required_cents}¢ (Package: {package_type})...")
            topup_res = await client.topup_credits(agent_id=AGENT_ID, package=package_type)
            logger.success(f"✅ New Balance: {topup_res.get('new_balance_cents', 'Unknown')}¢")

            # ⚡ Bolt Optimization: Process leads concurrently instead of sequentially
            # Reuses the single HTTPX client connection pool for maximum throughput
            tasks = [process_lead(lead, client, AGENT_ID) for lead in leads]
            await asyncio.gather(*tasks)

        except Exception as e:
            logger.critical(f"Agent Crash: {e}")

if __name__ == "__main__":
    asyncio.run(run_sniper())
